# Generated by Django 4.2.3 on 2024-04-02 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_activity_folder_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='activity',
        ),
        migrations.AddField(
            model_name='activity',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.file'),
        ),
        migrations.AlterField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='folder_name',
            field=models.CharField(default='My OneBox', max_length=255),
        ),
    ]
