# Generated by Django 4.2.3 on 2024-04-02 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_file_activity_activity_file_alter_file_folder_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activity',
            new_name='FileActivity',
        ),
        migrations.CreateModel(
            name='FolderActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.folder')),
            ],
        ),
    ]
