# Generated by Django 4.2.3 on 2024-04-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_file_folderactivity_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='uid',
            field=models.UUIDField(null=True),
        ),
    ]
