# Generated by Django 4.2.3 on 2024-04-09 10:54

import core.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_file_uid_folder_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=core.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='file',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default/image.png', null=True, upload_to=core.models.user_profile_image_directory_path),
        ),
    ]
