# Generated by Django 4.2.3 on 2024-04-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_file_file_alter_file_uid_alter_folder_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='trash',
            field=models.BooleanField(default=False),
        ),
    ]
